apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vx1uh3104-go
  janus-idp.io/tekton: vx1uh3104-go
  backstage.io/kubernetes-id: vx1uh3104-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vx1uh3104-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
