apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vx1uh3104-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vx1uh3104-go 
  name: vx1uh3104-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vx1uh3104-go 
